"""
Django settings for aguapei_backend project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from datetime import timedelta
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-34yxwhlf5qj&*dn4xh_^u(mw5ef8*%2cw&%z&^)@rf_z-z0uy8'
DEBUG = True
# Em desenvolvimento mobile o app pode chamar a API via 10.0.2.2
# (Android Emulator) ou pelo IP local da maquina na rede.
ALLOWED_HOSTS = ['*'] if DEBUG else []

# =======================================================================
# APLICAÇÕES
# =======================================================================
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api',
]

# =======================================================================
# MIDDLEWARE
# =======================================================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aguapei_backend.urls'

# =======================================================================
# TEMPLATES
# =======================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aguapei_backend.wsgi.application'

# =======================================================================
# BANCO DE DADOS
# =======================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Barco_Hotel',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# =======================================================================
# INTERNACIONALIZAÇÃO
# =======================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'api.Usuario'

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'api.hashers.LegacyBCryptPasswordHasher',
]

# =======================================================================
# CORS (Correto)
# =======================================================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization", 
    "content-type",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]

# =======================================================================
# AUTENTICACAO JWT
# =======================================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

