"""
Django settings for aguapei_backend project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-34yxwhlf5qj&*dn4xh_^u(mw5ef8*%2cw&%z&^)@rf_z-z0uy8'
DEBUG = True
ALLOWED_HOSTS = []

# =======================================================================
# APLICAÇÕES
# =======================================================================
# Esta lista está correta, limpa e minimalista.
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
]

# =======================================================================
# MIDDLEWARE
# =======================================================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # 🚀 REMOVIDO: Esta linha depende do 'django.contrib.auth', que não usamos.
    # 'django.contrib.auth.middleware.AuthenticationMiddleware', 
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aguapei_backend.urls'

# =======================================================================
# TEMPLATES
# =======================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                
                # 🚀 REMOVIDO: Este processador depende do 'django.contrib.auth'.
                # 'django.contrib.auth.context_processors.auth',
                
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aguapei_backend.wsgi.application'

# =======================================================================
# BANCO DE DADOS
# =======================================================================
# (Suas configurações de banco estão corretas)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Barco_Hotel',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# =======================================================================
# VALIDADORES DE SENHA
# =======================================================================
# 🚀 REMOVIDO: Este bloco inteiro depende do 'django.contrib.auth'.
# AUTH_PASSWORD_VALIDATORS = [ ... ]


# =======================================================================
# INTERNACIONALIZAÇÃO
# =======================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =======================================================================
# CORS (Correto)
# =======================================================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization", # <-- Correto, necessário para seu JWT
    "content-type",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]

# =======================================================================
# REST FRAMEWORK
# =======================================================================
# 🚀 REMOVIDO: Este bloco depende do 'rest_framework' e 'auth',
# que não estão mais em INSTALLED_APPS.
# REST_FRAMEWORK = { ... }


# =======================================================================
# 🚀 NOSSA CORREÇÃO FINAL PARA O ERRO DE MIGRAÇÃO
# =======================================================================
# Isso diz ao Django para NUNCA checar as migrações do app 'api'.
# Como usamos SQL Puro, não precisamos de migrações.
# Isso corrige o erro 'NodeNotFoundError'.
MIGRATION_MODULES = {
    'api': None,
}