# Generated by Django 4.2 on 2026-09-17 13:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barco',
            fields=[
                ('id_barco', models.AutoField(primary_key=True, serialize=False)),
                ('nome_barco', models.CharField(max_length=100)),
                ('capacidade_pessoas', models.IntegerField()),
                ('status_barco', models.CharField(default='Disponível', max_length=30)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'barco',
                'ordering': ['nome_barco'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaLavanderia',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.CharField(default='Ativo', max_length=20)),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'categoria_lavanderia',
                'ordering': ['ordem_exibicao', 'nome_categoria'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100)),
                ('tipo_categoria', models.CharField(max_length=30)),
                ('ativo', models.CharField(default='Ativo', max_length=20)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'categoria_produto',
                'ordering': ['tipo_categoria', 'nome_categoria'],
            },
        ),
        migrations.CreateModel(
            name='ContaConsumo',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('total_acumulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status_conta', models.CharField(default='Aberta', max_length=30)),
                ('dt_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_fechamento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conta_consumo',
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id_hospede', models.AutoField(primary_key=True, serialize=False)),
                ('nome_hospede', models.CharField(max_length=100)),
                ('email_hospede', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('pais_origem', models.CharField(max_length=50)),
                ('passaporte', models.CharField(blank=True, max_length=30, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('ativo', models.CharField(default='Ativo', max_length=20)),
            ],
            options={
                'db_table': 'hospede',
            },
        ),
        migrations.CreateModel(
            name='ItemVendaConsumo',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'item_venda_consumo',
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id_quarto', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('tipo_quarto', models.CharField(max_length=30)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_quarto', models.CharField(default='Disponível', max_length=30)),
            ],
            options={
                'db_table': 'quarto',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('observacao_reserva', models.TextField(blank=True, null=True)),
                ('status_reserva', models.CharField(default='Agendada', max_length=30)),
                ('status_pagamento', models.CharField(default='Pendente', max_length=30)),
                ('data_embarque', models.DateField(blank=True, null=True)),
                ('data_desembarque', models.DateField(blank=True, null=True)),
                ('local_embarque', models.CharField(blank=True, max_length=120, null=True)),
                ('local_desembarque', models.CharField(blank=True, max_length=120, null=True)),
                ('status_operacional', models.CharField(default='A Preparar', max_length=30)),
                ('observacao_operacional', models.TextField(blank=True, null=True)),
                ('barco', models.ForeignKey(blank=True, db_column='fk_barco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas', to='api.barco')),
                ('hospede_titular', models.ForeignKey(blank=True, db_column='fk_hospede_titular', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_titular', to='api.hospede')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='TipoPasseio',
            fields=[
                ('id_tipo_passeio', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.CharField(default='Ativo', max_length=20)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tipo_passeio',
                'ordering': ['nome_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email_usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(max_length=30)),
                ('ativo', models.CharField(default='Ativo', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='VendaConsumo',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('origem', models.CharField(max_length=30)),
                ('status_venda', models.CharField(default='Confirmada', max_length=30)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('total_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('conta', models.ForeignKey(db_column='fk_conta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendas', to='api.contaconsumo')),
                ('reserva', models.ForeignKey(db_column='fk_reserva', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendas_consumo', to='api.reserva')),
                ('usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendas_consumo', to='api.usuario')),
            ],
            options={
                'db_table': 'venda_consumo',
            },
        ),
        migrations.CreateModel(
            name='ServicoLavanderia',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_horas', models.IntegerField(default=24)),
                ('ativo', models.CharField(default='Ativo', max_length=20)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicos', to='api.categorialavanderia')),
            ],
            options={
                'db_table': 'servico_lavanderia',
                'ordering': ['nome_servico'],
            },
        ),
        migrations.CreateModel(
            name='ReservaQuarto',
            fields=[
                ('id_reserva_quarto', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('valor_diaria_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quarto', models.ForeignKey(db_column='fk_quarto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_quarto', to='api.quarto')),
                ('reserva', models.ForeignKey(db_column='fk_reserva', on_delete=django.db.models.deletion.DO_NOTHING, related_name='quartos_reservados', to='api.reserva')),
            ],
            options={
                'db_table': 'reserva_quarto',
            },
        ),
        migrations.CreateModel(
            name='ReservaPasseioDia',
            fields=[
                ('id_reserva_passeio_dia', models.AutoField(primary_key=True, serialize=False)),
                ('dia_viagem', models.IntegerField()),
                ('data_passeio', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('local_previsto', models.CharField(blank=True, max_length=120, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('reserva', models.ForeignKey(db_column='fk_reserva', on_delete=django.db.models.deletion.DO_NOTHING, related_name='passeios_dia', to='api.reserva')),
                ('tipo_passeio', models.ForeignKey(blank=True, db_column='fk_tipo_passeio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_passeio_dia', to='api.tipopasseio')),
            ],
            options={
                'db_table': 'reserva_passeio_dia',
            },
        ),
        migrations.CreateModel(
            name='ReservaHospede',
            fields=[
                ('id_reserva_hospede', models.AutoField(primary_key=True, serialize=False)),
                ('hospede', models.ForeignKey(db_column='fk_hospede', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_acompanhante', to='api.hospede')),
                ('reserva', models.ForeignKey(db_column='fk_reserva', on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospedes_adicionais', to='api.reserva')),
            ],
            options={
                'db_table': 'reserva_hospede',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_passeio',
            field=models.ForeignKey(blank=True, db_column='fk_tipo_passeio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas', to='api.tipopasseio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_criadas', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('controla_estoque', models.BooleanField(default=False)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('ativo', models.CharField(default='Ativo', max_length=20)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='api.categoriaproduto')),
            ],
            options={
                'db_table': 'produto',
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='OrdemLavanderia',
            fields=[
                ('id_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('status_ordem', models.CharField(default='Recebido', max_length=30)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('total_ordem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dt_recebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_previsao_entrega', models.DateTimeField(blank=True, null=True)),
                ('dt_entrega', models.DateTimeField(blank=True, null=True)),
                ('dt_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('conta', models.ForeignKey(db_column='fk_conta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_lavanderia', to='api.contaconsumo')),
                ('reserva', models.ForeignKey(db_column='fk_reserva', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_lavanderia', to='api.reserva')),
                ('usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_lavanderia', to='api.usuario')),
            ],
            options={
                'db_table': 'ordem_lavanderia',
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id_movimento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimento', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('estoque_anterior', models.IntegerField()),
                ('estoque_posterior', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_venda', models.ForeignKey(blank=True, db_column='fk_item_venda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimentos_estoque', to='api.itemvendaconsumo')),
                ('produto', models.ForeignKey(db_column='fk_produto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimentos_estoque', to='api.produto')),
                ('usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimentos_estoque', to='api.usuario')),
            ],
            options={
                'db_table': 'movimento_estoque',
            },
        ),
        migrations.AddField(
            model_name='itemvendaconsumo',
            name='produto',
            field=models.ForeignKey(db_column='fk_produto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens_vendidos', to='api.produto'),
        ),
        migrations.AddField(
            model_name='itemvendaconsumo',
            name='venda',
            field=models.ForeignKey(db_column='fk_venda', on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens', to='api.vendaconsumo'),
        ),
        migrations.CreateModel(
            name='ItemOrdemLavanderia',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordem', models.ForeignKey(db_column='fk_ordem', on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens', to='api.ordemlavanderia')),
                ('servico', models.ForeignKey(db_column='fk_servico', on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens_ordem', to='api.servicolavanderia')),
            ],
            options={
                'db_table': 'item_ordem_lavanderia',
            },
        ),
        migrations.CreateModel(
            name='HistoricoLavanderiaStatus',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('status_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('status_novo', models.CharField(max_length=30)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordem', models.ForeignKey(db_column='fk_ordem', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_status', to='api.ordemlavanderia')),
                ('usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historicos_lavanderia', to='api.usuario')),
            ],
            options={
                'db_table': 'historico_lavanderia_status',
            },
        ),
        migrations.AddField(
            model_name='contaconsumo',
            name='reserva',
            field=models.OneToOneField(db_column='fk_reserva', on_delete=django.db.models.deletion.DO_NOTHING, related_name='conta_consumo', to='api.reserva'),
        ),
    ]
